<?php

if(!$this->getConfig('enabled')) return;
?>
<?php if(!count($this->getItemCollection()->getItems())) return; ?>
<?php
    // getConfig
    $widthImage     = $this->getConfig('widthImage') ? $this->getConfig('widthImage') : 135;
    $heightImage    = $this->getConfig('heightImage') ? $this->getConfig('heightImage') : 135;
    $price          = $this->getConfig('price');
    $cart           = $this->getConfig('cart');
    // $compare        = $this->getConfig('compare');
    // $wishlist       = $this->getConfig('wishlist');
    $review         = $this->getConfig('review');
    //$rows           = $this->getConfig('rows');
    // $class          = ($rows > 1) ? '.slide-multirows' : '.products-grid';

?>
<div class="upsellslider category-products">
    <?php echo $this->getConfig('title') ? '<div class="upsell-title bx-title"><h2 class="title">' .$this->getConfig('title'). '</h2></div>' : ''; ?>
    <div class="products-grid">
    <?php // $this->setColumnCount(5); // uncomment this line if you want to have another number of columns. also can be changed in layout ?>
    <?php $this->resetItemsIterator() ?>
    <?php for($_i=0;$_i<$this->getRowCount();$_i++): ?>
        <?php for($_j=0;$_j<$this->getColumnCount();$_j++): ?>
            <?php if($_link=$this->getIterableItem()): ?>
            <div class="item"> 
                <div class="item-inner">
                    <div class="box-images">
                        <a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>" class="product-image">
                        <img src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image')->resize($widthImage, $heightImage) ?>" alt="<?php echo $this->htmlEscape($_link->getName()) ?>" />
                        </a>
                    </div>
                    <div class="product-shop">
                        <h2 class="product-name"><a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>"><?php echo $this->htmlEscape($_link->getName()) ?></a></h2>
                       <?php if( $price ): ?>
                            <?php echo $this->getPriceHtml($_link, true, '-upsell') ?>
                        <?php endif; ?>
                        <?php if($cart): ?>
                            <?php if($_link->isSaleable()): ?>
                                <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_link) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                            <?php else: ?>
                                <div class="availability out-of-stock"><span><i class="icon icon-bag color_primary"></i><?php echo $this->__('Out of stock') ?></span></div>
                            <?php endif; ?>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
            <?php endif; ?>
        <?php endfor; ?>
    <?php endfor; ?>
    </div>
</div>

<script type="text/javascript">
    jQuery(document).ready(function($){
        (function(selector){
            var $content = $(selector);
            var $slider  = $('.products-grid', $content);
            var slider   = $slider.owlCarousel({
                        <?php if($this->getConfig('autoPlay') == 0): ?>
                        autoplay: false, 
                        <?php else: ?>
                        autoplay: true,
                        <?php endif; ?>
                        autoplaySpeed: <?php echo $this->getSlideSpeed()?$this->getSlideSpeed():$this->getConfig('slideSpeed'); ?>, 
                        nav: <?php echo ($this->getConfig('navigation') == 1? "true": "false"); ?>, 
                        dots: <?php echo ($this->getConfig('pagination') == 1? "true": "false"); ?>, 
                        loop: <?php echo ($this->getConfig('loop') == 1? "true": "false") ?>,
                        autoplayHoverPause: <?php echo ($this->getConfig('stopOnHover') == 1? "true": "false"); ?>,
                        responsive: {<?php echo ($this->getResponsive()?$this->getResponsive():$this->getConfig('responsive')) ?>},
                        margin: <?php echo $this->getConfig('margin') ?>,
                        //padding: 10
                    })

        })(".upsellslider");
    });
</script>

