<?php
if(!Mage::getStoreConfig('relatedslider/general/enabled')) return;
?>
<?php if(!$this->getItems()->getSize()) return; ?>
<?php
    $_helper = Mage::helper('relatedslider');
    // getConfig
    $widthImage     = $_helper->getConfig('widthImage') ? $_helper->getConfig('widthImage') : 135;
    $heightImage    = $_helper->getConfig('heightImage') ? $_helper->getConfig('heightImage') : 135;
    $price          = $_helper->getConfig('price');
    $cart           = $_helper->getConfig('cart');
    // $compare        = $this->getConfig('compare');
    $wishlist       = $_helper->getConfig('wishlist');
    $review         = $_helper->getConfig('review');
    $rows           = Mage::getStoreConfig('relatedslider/general/rows');

    // $class          = ($rows > 1) ? '.slide-multirows' : '.products-grid';
?>

<div class="relatedslider">
    <?php echo $_helper->getConfig('title') ? '<div class="bx-title related-title"><h2 class="title">' .$_helper->getConfig('title'). '</h2></div>' : ''; ?>
    
    <div class="products-grid" id="block-related">
    <?php foreach($this->getItems() as $_item): ?>
        <div class="item">
            <div class="item-inner">
                <input type="checkbox" class="checkbox related-checkbox" id="related-checkbox<?php echo $_item->getId() ?>" name="related_products[]" value="<?php echo $_item->getId() ?>" />
                <div class="box-images">
                    <a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize( $widthImage, $heightImage ) ?>" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" /></a>
                </div>
                <div class="product-shop">
                    <h2 class="product-name">
                        <a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a>
                    </h2>
                    <div class="stock clearfix">
                        <?php if( $price ): ?>
                            <?php echo $this->getPriceHtml($_item, true, '-related') ?>
                        <?php endif; ?>
                        <?php if( $review ): ?>
                            <?php echo $this->getReviewsSummaryHtml($_item) ?>
                        <?php endif; ?>
                    </div>
                    <ul class="add-to-links clearfix">
                        <?php if($_item->isSaleable()): ?>
                            <li class="cart"><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_item) ?>')"><span><span><i class="icon icon-bag color_primary"></i><?php echo $this->__('Add to Bag') ?></span></span></button></li>
                        <?php else: ?>
                            <li><button title="<?php echo $this->__('Out of stock') ?>" class="button btn-cart availability out-of-stock"><span><span><i class="icon icon-bag color_primary"></i><?php echo $this->__('Out of stock') ?></span></span></button></li>
                        <?php endif; ?>
                    </ul>
                </div>
            </div>
        </div>
    <?php endforeach ?>
    </div>
</div>
<script type="text/javascript">decorateList('block-related', 'none-recursive')</script>
<script type="text/javascript">
    //<![CDATA[
    $$('.related-checkbox').each(function(elem){
        Event.observe(elem, 'click', addRelatedToProduct)
    });

    var relatedProductsCheckFlag = false;
    function selectAllRelated(txt){
        if (relatedProductsCheckFlag == false) {
            $$('.related-checkbox').each(function(elem){
                elem.checked = true;
            });
            relatedProductsCheckFlag = true;
            txt.innerHTML="<?php echo $this->__('unselect all') ?>";
        } else {
            $$('.related-checkbox').each(function(elem){
                elem.checked = false;
            });
            relatedProductsCheckFlag = false;
            txt.innerHTML="<?php echo $this->__('select all') ?>";
        }
        addRelatedToProduct();
    }

    function addRelatedToProduct(){
        var checkboxes = $$('.related-checkbox');
        var values = [];
        for(var i=0;i<checkboxes.length;i++){
            if(checkboxes[i].checked) values.push(checkboxes[i].value);
        }
        if($('related-products-field')){
            $('related-products-field').value = values.join(',');
        }
    }

    jQuery(document).ready(function($){
        (function(selector){
            var $content = $(selector);
            var $slider  = $('.products-grid', $content);
            var slider   = $slider.owlCarousel({
                        <?php if(Mage::getStoreConfig('relatedslider/general/items') == 0): ?>
                        autoplay: false, 
                        <?php else: ?>
                        autoplay: true,
                        <?php endif; ?>
                        autoplaySpeed: <?php echo $this->getSlideSpeed()?$this->getSlideSpeed():Mage::getStoreConfig('relatedslider/general/slideSpeed'); ?>, 
                        nav: <?php echo (Mage::getStoreConfig('relatedslider/general/navigation') == 1? "true": "false"); ?>, 
                        dots: <?php echo (Mage::getStoreConfig('relatedslider/general/pagination') == 1? "true": "false"); ?>, 
                        loop: <?php echo (Mage::getStoreConfig('relatedslider/general/loop') == 1? "true": "false") ?>,
                        autoplayHoverPause: <?php echo (Mage::getStoreConfig('relatedslider/general/stopOnHover') == 1? "true": "false"); ?>,
                        responsive: {<?php echo ($this->getResponsive()?$this->getResponsive():Mage::getStoreConfig('relatedslider/general/responsive')) ?>},
                        margin: <?php echo Mage::getStoreConfig('relatedslider/general/margin') ?>,
                        //padding: 10
                    })
        })(".relatedslider");
    });

    //]]>
</script>
