<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Blog
 * @version    tip
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */

?>
<div class="block">
<div class="block-title">
        <strong><span>Designers</span></strong>
    </div>
</div>
<?php
echo $this->getToolbarHtml();        
?>
<?php $posts = $this->getPosts(); ?>
<div id="messages_product_view">
    <?php Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true)); ?>
    <?php echo Mage::app()->getLayout()->getMessagesBlock()->getGroupedHtml(); ?>
</div>

<?php echo $this->getChildHtml('custom_designer_comments_toolbar'); ?>
<div class="row">
<?php foreach ($posts as $post): ?>
    <div class="col-sm-4">
        <div class="postWrapper">
             <a href="<?php echo Mage::getBaseUrl()."designer/designer/view/id/".$post->getId(); ?>"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$post->getImage(); ?>" ></a>
            <div class="postTitle">
                <h2><a href="<?php echo Mage::getBaseUrl()."designer/designer/view/id/".$post->getId(); ?>" ><?php echo $post->getName(); ?></a></h2>
            </div>
            <div class="postContent std"><?php echo $post->getDescription(); ?></div>
            
        </div>
    </div> 
<?php endforeach; ?>
</div>
<?php echo $this->getChildHtml('custom_designer_comments_toolbar'); ?>