<?php
$id = $this->getRequest()->getParam('id');
$designers = $this->getDesigner($id);
//echo "<pre>";print_r($designers->getData());
$media = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
$base =  Mage::getBaseUrl();

foreach($designers as $designer){
    $image = $designer->getImage();
    $name = $designer->getName();
    $city = $designer->getCity();
    $institute = $designer->getInstitute();
    $social_link = $designer->getSocialLink();
    $content = $designer->getDescription();
    ?>
    <div class="postWrapper">
    <?php echo $name;?>
    </div>
    <img src="<?php echo $media.$image;?>" title="<?php echo $name;?>" alt="<?php echo $name;?>">
    <h2> City : <?php echo $city;?></h2>
    <h2> Institute : <?php echo $institute;?></h2>
    <h2> Social Link : <a href="<?php echo $social_link;?>"><?php echo $social_link;?></a></h2>
    <h2>About : <?php echo $content;?></h2>
<?php }
?>