<?php

$id = $this->getRequest()->getParam('id');

$designers = $this->getDesigner($id);

//echo "<pre>";print_r($designers->getData());

$media = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);

$base =  Mage::getBaseUrl();



foreach($designers as $designer){

    $image = $designer->getImage();

    $name = $designer->getName();

    $city = $designer->getCity();

    $institute = $designer->getInstitute();

    $social_link = $designer->getSocialLink();

    $content = $designer->getDescription();

    ?>




    
    <div class="designer-view">
        <div class="bb-block">
            <div class="profile-image">
                <img src="<?php echo $media.$image;?>" title="<?php echo $name;?>" alt="<?php echo $name;?>">
             </div>
            <div class="designer-detials">
                <div class="desinger">Desinger</div>
                
                <div class="designer-name"><?php echo $name;?></div>
                <h2><span><?php echo $content;?></span></h2>

              

                <h2><span class="designer-place"><?php echo $city;?></span></h2>

                <h2><span class="designer-institute"><?php echo $institute;?></span></h2>
                <div class="social_link">
                    <a href="<?php echo $social_link;?>"><i class="fa fa-facebook"></i></a>

                    <a href="<?php echo $social_link;?>"><i class="fa fa-instagram"></i></a>

                      <a href="<?php echo $social_link;?>"><i class="fa fa-linkedin"></i></a>
                </div>

                


            </div>
        </div>
    </div>
<div class="test" style="padding-top: 100px;">
<?php }


$collection = Mage::getModel('catalog/product')->getCollection()->addAttributeToSelect('*');
$_productCollection = $collection->addAttributeToFilter('designer', $id);
$_helper = $this->helper('catalog/output');
    $helpLabels = $this->helper('themevast/labels');
// print_r($_productCollection->getData());

?>

<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>

<div class="category-products">

    <?php // Grid Mode ?>

    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = 20 ?>
    <?php $i=0; foreach ($_productCollection as $_product): ?>
    <?php  
            $designer_id = $_product->getDesigner();
            $collection = Mage::getModel('designer/designer')->getCollection();
            $collection->addFieldToFilter('designer_id',$designer_id);
    ?>
        <?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid row">
        <?php endif ?>
            <li class="item col-md-3 col-sm-6 col-xs-6 <?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                    <div class="item-inner">
                        <div class="box-images">
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                            <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(300, 300); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                            
                            <ul class="add-to-links">
                                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                    <li class="wishlist"><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" title="<?php echo $this->__('Add to Wishlist') ?>" class="link-wishlist"><i class="fa fa-heart"></i><?php //echo $this->__('Add to Wishlist') ?></a></li>
                                <?php endif; ?>
                                <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                    <li class="compare"><a href="<?php echo $_compareUrl ?>" title="<?php echo $this->__('Add to Compare') ?>" class="link-compare"><i class="fa fa-exchange"></i><?php //echo $this->__('Add to Compare') ?></a></li>
                                <?php endif; ?>
                                <?php if($_product->isSaleable()): ?>
                                <li class="quickview"><a class="view-detail" <?php if(Mage::getStoreConfig('quickview/general/enabled')):?> id='fancybox<?php echo $_product->getId()?>'  href="<?php echo $this->getUrl('quickview/index/ajax',array('product_id'=>$_product->getId())); ?>"<?php else: ?> href="<?php echo $_product->getProductUrl() ?>" href="<?php echo $_product->getProductUrl() ?>" <?php endif ?> title="<?php echo $this->__('Quick View') ?>"><i class="fa fa-search"></i></a></li>       
                            <?php endif; ?>
                            </ul>
                        </div>
                        <div class="product-shop">
                            <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                           <div class="product-name">
                            <?php  foreach ($collection as $designer) {
                                // echo "Designed by : <span style='font-size:14px;font-weight:500;'>".$designer->getName()."</span>";
                            }?>
                           </div>
                                <?php echo $this->getPriceHtml($_product, true) ?>
                                <?php //if($_product->getRatingSummary()): ?>
                                    <?php //echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                                <?php //endif; ?>
                            <?php if($_product->isSaleable()): ?>
                                    <button type="button" title="<?php echo $this->__('Add to Bag') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                                <?php else: ?>
                                    <button title="<?php echo $this->__('Out of stock') ?>" class="button btn-cart availability out-of-stock"><span><span><?php echo $this->__('Out of stock') ?></span></span></button>
                                <?php endif; ?>
                            
                        </div>
                        <div class="new-sale">
                            <?php echo $helpLabels->getLabels($_product); //Product labels ?>
                        </div>
                    </div>   
            </li>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </ul>
        <?php endif ?>
        <?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>

    <div class="toolbar-bottom">
        <!-- <?php echo $this->getToolbarHtml() ?> -->
    </div>
</div>
<?php endif; ?>

</div>