<?php
	if(!$this->getConfig('enabled')) return;
	$_productCollection=$this->getProductCollection();
	$_helper = $this->helper('catalog/output');
	//$helpLabels = $this->helper('themevast/labels');
?>
<?php
	// getConfig
	$widthImage  	= $this->getConfig('widthImage') ? $this->getConfig('widthImage') : 135;
	$heightImage 	= $this->getConfig('heightImage') ? $this->getConfig('heightImage') : 135;
	$price   		= $this->getShowPrice()?$this->getShowPrice():$this->getConfig('price');
	$cart    		= $this->getShowButton()?$this->getShowButton():$this->getConfig('cart');
	$compare  		= $this->getShowButton()?$this->getShowButton():$this->getConfig('compare');
	$wishlist  		= $this->getShowButton()?$this->getShowButton():$this->getConfig('wishlist');
	$review  		= $this->getShowReview()?$this->getShowReview():$this->getConfig('review');
	$slide  		= $this->getEnableSlide()?$this->getEnableSlide():$this->getConfig('slide');
	if($slide == 1){
		$rows 		= $this->getRows()?$this->getRows():$this->getConfig('rows');
	}else{
		$rows 		= 1;	
	}
	$random 		= $this->generateRandomString();

	$limit 			= $this->getLimit()?$this->getLimit():'';
	$col 			= $this->getColumn()?round(12/$this->getColumn()):4;
?>
<div class="box-products-slider">
	<div class="row">
		<div class="col-xs-12 col-md-6">
			<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('banner_product1')->toHtml() ?>
		</div>
		<div class="col-xs-12 col-md-6">
			<div class="featuredproduct" id="featuredproduct-<?php echo $random; ?>">
					<?php //echo $this->getConfig('title') ? '<div class="bx-title featured-title"><h2>' .$this->getConfig('title'). '</h2></div>' : '';
					?>
					<?php //if($this->getConfig('desciption')): ?>
					<?php //echo $this->getConfig('desciption') ?>
					<?php //endif; ?>
				<?php if(!$_productCollection->count()): ?> 
						<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
					<?php else: ?>
				<div class="box-slider">
					<div class="products-grid <?php if($slide != 1): ?>row<?php endif; ?>">
				    	<?php $_collectionSize = $_productCollection->count() ?>
				    	<?php $_columnCount = $this->getColumnCount(); ?>
				    	<?php $j=0; $time = $this->getConfig('playDelay') ? $this->getConfig('playDelay') : 0; ?>
				    	<?php $i=0; $k=0; foreach ($_productCollection as $_product): ?>
						<?php $t = $j*$time; $t .='ms'; $j++; ?>
						<?php if ($i++%$rows==0): ?>
							<div class="<?php if($slide != 1): ?>col-md-<?php echo $col; ?> col-sm-6 col-sms-6 col-smb-12 <?php endif; ?> item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?> item-animate">
						<?php endif ?>
							<div class="item-inner">
								<div class="box-images">
									<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
									<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($widthImage, $heightImage); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
									</a>
								</div>
								<div class="product-shop">
									<h2 class="product-name">
										<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a>
									</h2>
				                    <?php if($price): ?>
										<?php echo $this->getPriceHtml($_product, true) ?>
									<?php endif; ?>
								</div>
								<ul class="add-to-links clearfix">
									<?php if($cart): ?>
					    				<?php if($_product->isSaleable()): ?>
					    				    <li class="cart"><button type="button" title="<?php echo $this->__('Add to Bag') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><i class="icon icon-bag color_primary"></i><?php echo $this->__('Add to cart') ?></span></span></button></li>
					    				<?php else: ?>
					    				<li class="cart"><button title="<?php echo $this->__('Out of stock') ?>" class="button btn-cart availability out-of-stock"><span><span><?php echo $this->__('Out of stock') ?></span></span></button></li>
					    				<?php endif; ?>
				    			    <?php endif; ?>
				    			    <?php if($wishlist): ?>
			                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
			                                <li class="wishlist"><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" title="<?php echo $this->__('Add to Wishlist') ?>" class="link-wishlist"><i class="icon icon-heart"></i><?php //echo $this->__('Add to Wishlist') ?></a></li>
			                            <?php endif; ?>
			                        <?php endif; ?>
			                        <?php if($compare): ?>
			                            <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
			                                <li class="compare"><a href="<?php echo $_compareUrl ?>" title="<?php echo $this->__('Add to Compare') ?>" class="link-compare"><?php //echo $this->__('Add to Compare') ?><i class="icon icon-shuffle"></i></a></li>
			                            <?php endif; ?>
			                        <?php endif; ?>
								</ul>
				            </div>
						<?php if ($i%$rows==0 || $i%$_productCollection->count()==0): ?>
							</div>
						<?php endif ?>
						<?php if(++$k == $limit) break; ?>
						<?php endforeach ?>
					</div>
				<?php endif ?>
				</div>
				<?php if($slide == 1) : ?>
					<script type="text/javascript">
					jQuery(document).ready(function($){
						var selector = '#featuredproduct-<?php echo $random; ?>';
						(function(selector){
							var $content = $(selector);
							var $slider  = $('.products-grid', $content);
							var slider 	 = $slider.owlCarousel({
									<?php if($this->getConfig('autoPlay') == 0): ?>
									autoplay: false, 
									<?php else: ?>
									autoplay: true,
									<?php endif; ?>
									autoplaySpeed: <?php echo $this->getSlideSpeed()?$this->getSlideSpeed():$this->getConfig('slideSpeed'); ?>, 
									nav: <?php echo ($this->getConfig('navigation') == 1? "true": "false"); ?>, 
									dots: <?php echo ($this->getConfig('pagination') == 1? "true": "false"); ?>, 
									loop: <?php echo ($this->getConfig('loop') == 1? "true": "false") ?>,
									autoplayHoverPause: <?php echo ($this->getConfig('stopOnHover') == 1? "true": "false"); ?>,
									responsive: {<?php echo ($this->getResponsive()?$this->getResponsive():$this->getConfig('responsive')) ?>},
									margin: <?php echo ($this->getMargin()?$this->getMargin():$this->getConfig('margin')) ?>,
									//padding: 10 
								})

						})(selector);
						jQuery('.owl-item').children('a').parent().hide();
					});
					</script>
				<?php endif; ?>
			</div>
		</div>
	</div>
</div>







