<?php
$className = Mage::getConfig()->getBlockClassName('megamenu/megamenu');
            $block = new $className();  
 $_menu = $block->renderCategoriesMenuHtml(0,'level-top') ?>

<nav class="nav-container">
        <?php if($_menu): ?>
            <div class="nav-mobilemenu-container visible-xs visible-sm">
                <div class="navbar">
                        <div id="navbar-inner" class="navbar-inner navbar-inactive">
                                <div class="menu-mobile">
                                    <a class="btn-navbar navbar-toggle">
                                        <i class="icon-menu icons"></i>
                                        <span class="brand navbar-brand"><?php echo $this->__('Menu') ?></span>
                                    </a>
                                </div>
                                <ul id="nav-mobilemenu" class="mobilemenu nav-collapse collapse">
                                        <div id="close" class="close">close</div>
                                        <?php echo $_menu ?>
                                        <li class="blog level0 level-top"><a href="<?php echo $this->getUrl('blog')?>" class="level0" title="blog"><span><?php echo $this->__('Blog')?></span></a></li>
                                </ul>
                        </div>
                </div>
            </div>
        <?php endif ?>
        <div id="nav_megamenu" class="nav_megamenu visible-lg visible-md"> 
            <?php $megamenu =  $this->getLayout()->createBlock('megamenu/megamenu'); ?>       
            <?php echo $megamenu->drawMegamenuHome(); ?>
            <?php if(Mage::getStoreConfig('megamenu/general/showall')==1):?>
            <?php echo $megamenu->drawMegamenuAll();?>
            <?php else:?>
            <?php echo $megamenu->drawMegamenuMainTop(); ?>
            <?php endif;?>
            <?php echo $megamenu->drawMegamenuExtra(); ?>
            <?php echo $megamenu->drawMegamenuLink(); ?>
            
            
        </div>
    <script type="text/javascript">
    var MEGAMENU_EFFECT = <?php echo (int)Mage::getStoreConfig('megamenu/general/effect')?>;
    jQuery(window).scroll(function () {
      if (jQuery(this).scrollTop() > 200) {
       jQuery('nav').addClass("fix-nav");
      } else {
       jQuery('nav').removeClass("fix-nav");
      }
    });
    jQuery(".icon-menu").on('click', function (e) {
        e.stopPropagation();
    jQuery('#nav-mobilemenu').show("slide", { direction: "left" }, 200);
    jQuery('body').addClass('menu-open');
    });

jQuery('#nav-mobilemenu').click(function(e){
     e.stopPropagation();
})
jQuery("#close").on('click', function (e) {
    e.stopPropagation();
    jQuery('#nav-mobilemenu').hide("slide", { direction: "left" }, 500);
    jQuery('body').removeClass('menu-open');
});

jQuery(document).click( function(){
    jQuery('#nav-mobilemenu').hide("slide", { direction: "left" }, 500);
    jQuery('body').removeClass('menu-open');
});


    </script>
</nav>
